<?php

namespace Database\Seeders;

use App\Models\Patient;
use Illuminate\Database\Seeder;

class PatientsSeeder extends Seeder
{
    /**
     * Seed the patient registry. Idempotent — keyed by patient_id.
     */
    public function run(): void
    {
        $patients = [
            [
                'patient_id' => '24-021128',
                'name' => 'Angela Reyes',
                'first_name' => 'Angela',
                'middle_name' => 'M.',
                'last_name' => 'Reyes',
                'age' => 20,
                'type' => 'Student',
                'course_dept' => 'BS Computer Science',
                'block' => 'Block 1',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 912 345 6789',
                'emergency_contact' => 'Maria Reyes (Mother) - +63 912 345 6780',
                'emergency_contact_name' => 'Maria Reyes (Mother)',
                'emergency_contact_phone' => '+63 912 345 6780',
                'allergies' => 'Peanuts, Penicillin',
                'history' => 'Mild Asthma, Migraines',
                'status' => 'Active',
            ],
            [
                'patient_id' => '22-010941',
                'name' => 'Mark Dela Cruz',
                'first_name' => 'Mark',
                'middle_name' => 'T.',
                'last_name' => 'Dela Cruz',
                'age' => 22,
                'type' => 'Student',
                'course_dept' => 'BS Information Technology',
                'block' => 'Block 2',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 922 876 5432',
                'emergency_contact' => 'Tomas Dela Cruz (Father) - +63 922 876 5431',
                'emergency_contact_name' => 'Tomas Dela Cruz (Father)',
                'emergency_contact_phone' => '+63 922 876 5431',
                'allergies' => 'None',
                'history' => 'Gastroesophageal reflux disease (GERD)',
                'status' => 'Active',
            ],
            [
                'patient_id' => '21-011122',
                'name' => 'Joanna Lim',
                'first_name' => 'Joanna',
                'middle_name' => 'S.',
                'last_name' => 'Lim',
                'age' => 21,
                'type' => 'Student',
                'course_dept' => 'BEED Elementary Education',
                'block' => 'Block 1',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 933 222 1111',
                'emergency_contact' => 'Lim Sian (Father) - +63 933 222 0000',
                'emergency_contact_name' => 'Lim Sian (Father)',
                'emergency_contact_phone' => '+63 933 222 0000',
                'allergies' => 'Sulfa drugs',
                'history' => 'Allergic Rhinitis',
                'status' => 'Active',
            ],
            [
                'patient_id' => '23-010042',
                'name' => 'Alberto Ruiz',
                'first_name' => 'Alberto',
                'middle_name' => 'E.',
                'last_name' => 'Ruiz',
                'age' => 23,
                'type' => 'Student',
                'course_dept' => 'BS Mechanical Engineering',
                'block' => 'Block 3',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 944 123 9876',
                'emergency_contact' => 'Elena Ruiz (Mother) - +63 944 123 9870',
                'emergency_contact_name' => 'Elena Ruiz (Mother)',
                'emergency_contact_phone' => '+63 944 123 9870',
                'allergies' => 'Aspirin',
                'history' => 'Hypertension',
                'status' => 'Active',
            ],
            [
                'patient_id' => '23-010119',
                'name' => 'Susan Clave',
                'first_name' => 'Susan',
                'middle_name' => 'R.',
                'last_name' => 'Clave',
                'age' => 22,
                'type' => 'Student',
                'course_dept' => 'BS Business Administration',
                'block' => 'Block 1',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 955 456 7890',
                'emergency_contact' => 'Robert Clave (Father) - +63 955 456 7891',
                'emergency_contact_name' => 'Robert Clave (Father)',
                'emergency_contact_phone' => '+63 955 456 7891',
                'allergies' => 'Seafood',
                'history' => 'None',
                'status' => 'Active',
            ],
            [
                'patient_id' => '23-010881',
                'name' => 'John Paul Santos',
                'first_name' => 'John Paul',
                'middle_name' => 'L.',
                'last_name' => 'Santos',
                'age' => 21,
                'type' => 'Student',
                'course_dept' => 'BS Business Administration',
                'block' => 'Block 2',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 977 123 4567',
                'emergency_contact' => 'Lorna Santos (Mother) - +63 977 123 4568',
                'emergency_contact_name' => 'Lorna Santos (Mother)',
                'emergency_contact_phone' => '+63 977 123 4568',
                'allergies' => 'None',
                'history' => 'None',
                'status' => 'Active',
            ],
            [
                'patient_id' => '24-010012',
                'name' => 'Patricia Mae Garcia',
                'first_name' => 'Patricia Mae',
                'middle_name' => 'L.',
                'last_name' => 'Garcia',
                'age' => 20,
                'type' => 'Student',
                'course_dept' => 'BS Hospitality Management',
                'block' => 'Block 1',
                'address' => 'Tagum Norte, Trinidad, Bohol, Philippines',
                'nationality' => 'Filipino',
                'contact' => '+63 998 765 4321',
                'emergency_contact' => 'Leon Garcia (Father) - +63 998 765 4320',
                'emergency_contact_name' => 'Leon Garcia (Father)',
                'emergency_contact_phone' => '+63 998 765 4320',
                'allergies' => 'Dust Mites',
                'history' => 'Eczema',
                'status' => 'Active',
            ],
        ];

        foreach ($patients as $patient) {
            Patient::firstOrCreate(['patient_id' => $patient['patient_id']], $patient);
        }
    }
}
